CREATE SCHEMA BOTWA;

CREATE TABLE BOTWA.BOT_CONFIG (
    CONFIG_ID     INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PHONE_NUMBER  VARCHAR(30) NOT NULL,
    API_KEY       VARCHAR(100) NOT NULL,
    ACTIVE        CHAR(1) NOT NULL DEFAULT 'Y'
);

CREATE TABLE BOTWA.BOT_SESSION (
    SESSION_ID    BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PHONE_NUMBER  VARCHAR(30) NOT NULL,
    CURRENT_STATE VARCHAR(30) NOT NULL,
    LAST_OPTION   VARCHAR(10),
    CREATED_AT    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    STATUS        CHAR(1) NOT NULL DEFAULT 'A'
);

CREATE TABLE BOTWA.BOT_INBOUND (
    IN_ID         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PHONE_NUMBER VARCHAR(30) NOT NULL,
    MESSAGE_TEXT VARCHAR(1000) NOT NULL,
    PROCESSED    CHAR(1) NOT NULL DEFAULT 'N',
    CREATED_AT   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE BOTWA.BOT_OUTBOUND (
    OUT_ID        BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PHONE_NUMBER VARCHAR(30) NOT NULL,
    MESSAGE_TEXT VARCHAR(2000) NOT NULL,
    SENT_STATUS  CHAR(1) NOT NULL DEFAULT 'N',
    API_RESPONSE VARCHAR(5000),
    CREATED_AT   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    SENT_AT       TIMESTAMP
);

CREATE TABLE BOTWA.BOT_LOG (
    LOG_ID        BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PHONE_NUMBER VARCHAR(30),
    EVENT_TYPE    VARCHAR(30),
    EVENT_TEXT    VARCHAR(2000),
    CREATED_AT    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO BOTWA.BOT_CONFIG (PHONE_NUMBER, API_KEY)
VALUES ('+34123123123', '1234567890');